[package]
name = "todo"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4.31"
console = "0.15.7"
dialoguer = "0.11.0"
json = "0.12.4"
prettytable = "0.10.0"
